apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-caption-recommender
  labels:
    app: ai-caption-recommender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-caption-recommender
  template:
    metadata:
      labels:
        app: ai-caption-recommender
    spec:
      containers:
      - name: app
        image: ghcr.io/yourusername/ai-caption-recommender:latest
        ports:
        - containerPort: 8501
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-caption-recommender-service
spec:
  selector:
    app: ai-caption-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer